name: CI - Build & Push App

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load IMAGE variables
        run: |
          echo "GHCR_IMAGE=ghcr.io/${{ github.repository }}/llm-app" >> "$GITHUB_ENV"
          echo "IMAGE_SHA=${{ github.sha }}" >> "$GITHUB_ENV"

      - name: Build (no push) on PR to validate
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: app/Dockerfile
          push: false
          tags: |
            ${{ env.GHCR_IMAGE }}:pr-${{ github.event.pull_request.number }}

      - name: Build & Push on main
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_IMAGE }}:${{ env.IMAGE_SHA }}
            ${{ env.GHCR_IMAGE }}:latest
